## Code Explanation


1. First we read example Technical Skills file which will be used for training our model
2. We create list named as exTechlst which consists of list of all the technical skills used for training.
3. Since we only have positive values i.e only technical skills we read another text file to get non-technical values so we can properly train our model.
4. We need to process the values since they are continious sentences.  At first we apply work tokenizer to get seperate words and then we apply port Stemmer to extract root words.
5. we form another array of 1's and 0's so we can have target variable.
6. In X we have technical and non-Technical skills and in Y we have 1's and 0's
7. We split them in training and testing set of 80% and 20% respectively
8. We use GaussianNB classifier to classify the data.
9. Since we can't feed words directly to the model we use CountVectorizer to convert words into vectors.
10. After this process we train the model and check accuracy
11. After that we apply final data i.e. Raw_Skills_Dataset to model and classify it into 2  parts.

In [1]:
import numpy as np
from nltk.corpus import stopwords
from nltk.tokenize import  word_tokenize


In [2]:
import csv
exTech = []
with open("Example_Technical_Skills.csv", "r") as csvfile:
    reader_variable = csv.reader(csvfile, delimiter=",")
    for row in reader_variable:
        #print(row)
        exTech.append(row)
        
rawSkills = []
with open("Raw_Skills_Dataset.csv", "r",encoding='utf-8') as csvfile:
    reader_variable = csv.reader(csvfile, delimiter=",")
    for row in reader_variable:
        #print(row)
        rawSkills.append(row)

In [3]:
exTechlst = []
rawSkillslst = []

for i in exTech:
    for j in i:
       exTechlst.append(j) 
    
for i in rawSkills:
    for j in i:
       rawSkillslst.append(j)

In [4]:
exTechlst

['Technology Skills',
 'SAP Fiori Developer',
 'Oracle Instance Management & Strategy',
 'Boomi Master Data Management',
 'Digital Manufacturing on Cloud ( DMC)',
 'DevOps',
 'CA SAM',
 'OpenShift',
 'Acxiom Data Analytics',
 'SAP Digital Boardroom',
 'Seeburger BIS',
 'SAP Transport Management',
 'PeopleSoft Workflow',
 'NICE Actimize',
 'Oracle - Access Manager',
 'SAP Electronic Data Interchange (EDI)',
 'Ideas crowdsourcing',
 'PeopleSoft Workforce Planning',
 'SAP Benefits',
 'ONESOURCE R&D Credit Manager',
 'SAP Consignment',
 'MS Bot Framework',
 'IBM WebSphere Application Server',
 'Microsoft - Azure AD Domain Services',
 'SAP IBP / BPC',
 'Oracle Hyperion Capital Asset Planning',
 'SAP Introscope Wily',
 'EJB / RMI',
 'SAS Base',
 'Siebel Modules Non Functional Testing',
 'Oracle Cloud Product Hub Data Steward',
 'Kronos WFC Accruals Configuration',
 'JDE Fixed Assets',
 'SAP TM-EWM Integration',
 'PeopleSoft Payables',
 'NetSuite Case Management',
 'MySQL',
 'Escalations and 

In [5]:
rawSkillslst

['RAW DATA',
 'What ifs',
 'seniority',
 'familiarity',
 'functionalities',
 'Lambdas',
 'Java Streams',
 'Object Oriented analysis',
 'Relational Databases',
 'SQL',
 'ORM',
 'JPA2',
 'Hibernate',
 'MyBatis',
 'Hibernate',
 'code versioning tools',
 'Git.. Familiarity',
 'Maven',
 'Gradle.. Familiarity',
 'continuous integration',
 'continuous delivery development processes',
 'jenkins',
 'bamboo',
 'Familiarity',
 'frameworks',
 'transformations',
 'analytical reporting',
 'conceptual data models',
 'standard naming conventions',
 'coding practices',
 'consistency',
 'optimized solutions',
 'methodologies',
 'high throughput data access services',
 'analyze/profile data',
 'conceptual, logical & physical data model designs',
 'reporting and analytics solutions',
 'physical databases',
 'variances',
 'discrepancies',
 'all phases',
 'integrations',
 'Demonstrable experience',
 'logical and physical data models',
 'interpersonal skills',
 'modern enterprise data architectures',
 'data 

In [6]:
stop_words = list(stopwords.words('english'))
stop_words.sort()
stop_words

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [7]:
NonTech = []
with open("non_technicalSkills.txt", "r") as csvfile:
    reader_variable = csv.reader(csvfile, delimiter=",")
    for row in reader_variable:
        #print(row)
        NonTech.append(row)
        
NonTechlst = []
for i in NonTech:
    for j in i:
       NonTechlst.append(j) 
    
NonTechlst

['My name is Jane Doe',
 ' I’m 22 years old and I recently graduated from University X with a B.A. in international business. While there',
 ' I learned a lot of theory in subjects like corporate communication',
 ' international economics',
 ' corporate governance',
 ' and more. I was also part of the student government',
 ' and maintained a GPA of 3.6.',
 'I’ve worked hard in my education and now I’m ready to apply my knowledge into practice.',
 'While I don’t have any real-life work experience',
 ' I’ve had a lot of exposure to the business environment. A lot of my courses involved working with real companies to solve real problems.',
 'Now',
 ' I’m looking to leverage everything I’ve learned in uni and get some hands-on work experience.',
 'So',
 ' my name is John',
 ' and I’m a senior at School XYZ. ',
 'This year',
 ' I managed to maintain a 3.7 GPA',
 ' while working on a few different school projects. I started an ‘Ernest Hemingway Book Club’ which has up to 

In [8]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

NonTechlst2 = []
tokenWord = []
for i in NonTechlst:
    tokenWord.append(word_tokenize(i))
   
   
for i in tokenWord:
     for j in i:
        if j not in stop_words:
            NonTechlst2.append(ps.stem(j.lower()))
        
NonTechlst2

['my',
 'name',
 'jane',
 'doe',
 'i’m',
 '22',
 'year',
 'old',
 'i',
 'recent',
 'graduat',
 'univers',
 'x',
 'b.a',
 '.',
 'intern',
 'busi',
 '.',
 'while',
 'i',
 'learn',
 'lot',
 'theori',
 'subject',
 'like',
 'corpor',
 'commun',
 'intern',
 'econom',
 'corpor',
 'govern',
 '.',
 'i',
 'also',
 'part',
 'student',
 'govern',
 'maintain',
 'gpa',
 '3.6',
 '.',
 'i’v',
 'work',
 'hard',
 'educ',
 'i’m',
 'readi',
 'appli',
 'knowledg',
 'practic',
 '.',
 'while',
 'i',
 'don’t',
 'real-lif',
 'work',
 'experi',
 'i’v',
 'lot',
 'exposur',
 'busi',
 'environ',
 '.',
 'a',
 'lot',
 'cours',
 'involv',
 'work',
 'real',
 'compani',
 'solv',
 'real',
 'problem',
 '.',
 'now',
 'i’m',
 'look',
 'leverag',
 'everyth',
 'i’v',
 'learn',
 'uni',
 'get',
 'hands-on',
 'work',
 'experi',
 '.',
 'so',
 'name',
 'john',
 'i’m',
 'senior',
 'school',
 'xyz',
 '.',
 'thi',
 'year',
 'i',
 'manag',
 'maintain',
 '3.7',
 'gpa',
 'work',
 'differ',
 'school',
 'project',
 '.',
 

In [9]:
X = np.append(np.array(exTechlst),np.array(NonTechlst2))

In [10]:
y1 = [1]*len(exTechlst)
y2 = [0]*len(NonTechlst2)
Y = np.append(np.array(y1),np.array(y2))

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1425)
X1 = cv.fit_transform(X).toarray()
X1

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X1, Y, test_size = 0.20, random_state = 0)

In [13]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [14]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 42   3]
 [ 36 157]]


0.8361344537815126

In [16]:
finalClassification = cv.transform(rawSkillslst[1:]).toarray()
y_pred_final = classifier.predict(finalClassification)
print(y_pred_final)

[0 0 0 ... 1 0 0]


In [17]:
finalClassificationValues = np.column_stack([np.array(rawSkillslst[1:]),np.array(y_pred_final)])
           

In [18]:
finalClassificationValues

array([['What ifs', '0'],
       ['seniority', '0'],
       ['familiarity', '0'],
       ...,
       ['Self-motivated, enthusiastic and strong drive', '1'],
       ['negotiation', '0'],
       ['deadlines', '0']], dtype='<U120')